import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => readFile(path.join(root, file), 'utf8');
const escape = (value) => String(value).replace(/[&<>"']/g, (c) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
}[c]));
const tags = (items) => items.map((item) => '<li>' + escape(item) + '</li>').join('');
const data = JSON.parse(await read('content/portfolio.json'));
const cardTemplate = await read('src/components/project-card.html');
const render = (template, values) => template.replace(/{{([A-Z_]+)}}/g, (_, key) => {
  if (!(key in values)) throw new Error('Missing template value: ' + key);
  return values[key];
});
const projectCards = data.projects.map((project) => render(cardTemplate, {
  ID: escape(project.id), NUMBER: escape(project.number), EYEBROW: escape(project.eyebrow),
  TITLE: escape(project.title), SUMMARY: escape(project.summary), STATUS: escape(project.status),
  TAGS: tags(project.tags),
  DETAILS: project.details.map(([title, description]) =>
    '<div><dt>' + escape(title) + '</dt><dd>' + escape(description) + '</dd></div>').join('\n')
})).join('\n');
const html = render(await read('src/index.template.html'), {
  NAME: escape(data.profile.name), TITLE: escape(data.profile.title),
  COMPANY: escape(data.profile.company), INTRO: escape(data.profile.intro),
  ABOUT: escape(data.profile.about), ABOUT_MORE: escape(data.profile.aboutMore),
  EMAIL: escape(data.profile.email), PROJECTS: projectCards,
  GATE_DIAGRAM: await read('src/components/gate-diagram.html'),
  CAPABILITIES: data.capabilities.map((item) =>
    '<article class="service-card"><span class="service-number">' + escape(item.number) +
    '</span><h3>' + escape(item.title) + '</h3><p>' + escape(item.body) +
    '</p><ul class="tags" aria-label="Technologies">' + tags(item.tags) + '</ul></article>').join('\n'),
  SUPPORTING: data.supporting.map((item) => '<div><h3>' + escape(item.title) +
    '</h3><p>' + escape(item.body) + '</p></div>').join('\n'),
  CERTIFICATES: data.certificates.map((item) =>
    '<li><a href="' + escape(item.url) + '" target="_blank" rel="noopener noreferrer">' +
    '<span><strong>' + escape(item.title) + '</strong><small>' + escape(item.version) +
    '</small></span><span aria-hidden="true">↗</span><span class="sr-only"> — course information, opens in a new tab</span></a></li>').join('\n')
});
const output = '<!-- Generated by scripts/build.mjs. Edit src/ and content/portfolio.json. -->\n' + html.trimEnd() + '\n';
if (process.argv.includes('--check')) {
  if (await read('index.html') !== output) throw new Error('index.html is stale. Run node scripts/build.mjs.');
  console.log('Generated HTML is up to date.');
} else {
  await writeFile(path.join(root, 'index.html'), output, 'utf8');
  console.log('Built index.html from content and templates. No packages required.');
}
